name: nets

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install nets and its dependencies
        run: |
          pip install .
      - name: Test with pytest
        run: |
          pip install pytest
          pytest src/nets/tests/unit --disable-warnings
          pytest src/nets/tests/integration --disable-warnings